name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'
jobs:
  mutiny-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-09-19
          components: clippy
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-release-
            cargo-${{ runner.os }}-

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'v0.13.1'

      - name: Build wasm
        env:
          RUSTUP_TOOLCHAIN: nightly-2024-09-19
        run: wasm-pack build ./mutiny-wasm --release --weak-refs --target web --scope nervina-labs

      - name: Publish wasm
        run: wasm-pack publish --access public -t web
        env:
          RUSTUP_TOOLCHAIN: nightly-2024-09-19
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
